"""Tunable knobs for the AETHER kernel-optimization loop.

The loop keeps the hardware FIXED (one simulator, built once) and has the agent
optimize a single kernel file. Reward is cycle count; correctness is enforced by
the benchmark's own self-check, which the agent never touches.

Everything *benchmark*-specific now lives in `kernels.py` (one `Kernel` entry
per benchmark); everything *run*-specific is selected in `context.py` from
`loop.py`'s `--kernel` / `--config` flags. What is left here is global.
"""

from __future__ import annotations

import os
from pathlib import Path

# --- Workspace -------------------------------------------------------------
# Everything the loop reads/writes on the host hangs off AETHER_ROOT. It
# defaults to this example's own directory (the parent of loop/), so a fresh
# clone works without setting anything; point AETHER_ROOT elsewhere to keep
# run artifacts off the checkout.
AETHER_ROOT = Path(os.environ.get("AETHER_ROOT", Path(__file__).resolve().parent.parent))
# Saturn benchmark tree the loop compiles against (a saturn-vectors checkout).
BENCHMARKS_DIR = Path(os.environ.get(
    "AETHER_BENCHMARKS_DIR", AETHER_ROOT / "repos" / "saturn" / "benchmarks"))
OUT_DIR = Path(os.environ.get("AETHER_OUT_DIR", AETHER_ROOT / "out" / "loop"))

# --- Target (defaults; override per run with `loop.py --config NAME`) ------
# Shuttle + Saturn, VLEN=256 / DLEN=128. Non-cosim: the benchmark self-checks,
# so the loop does not depend on cospike. That is a choice, not a limitation —
# cospike on the co-existence config has since been verified working (see
# out/coexist/summary.txt: cosim_gemmini_tiled and cosim_rvv_sgemv both rc=0 on
# GENV256D128GemminiShuttleCosimConfig). Running the loop without it just keeps
# every iteration ~2x faster.
SIM_CONFIG = "GENV256D128GemminiShuttleConfig"
CONFIG_PACKAGE = "chipyard"
# Path to chipyard INSIDE the chisel-build container (not on the host).
CHIPYARD_PATH = os.environ.get("CHIPYARD_PATH", "/home/ray/chipyard")

# --- The kernel under optimization -----------------------------------------
# Default entry from kernels.KERNELS; override with `loop.py --kernel NAME`.
DEFAULT_KERNEL = "vec-sgemv"

# --- Cross-compile ---------------------------------------------------------
# Lifted verbatim from saturn/benchmarks/Makefile's compile_template. The only
# per-benchmark part is the `-I./<bench_dir>` include, hence `cflags()`.
CC = "riscv64-unknown-elf-gcc"
BASE_CFLAGS = [
    "-I./env", "-I./common",
    "-DPREALLOCATE=1", "-mcmodel=medany", "-static", "-O2", "-g",
    "-ffast-math", "-fno-common", "-fno-builtin-printf",
    "-fno-tree-loop-distribute-patterns",
    "-march=rv64gcv_zfh_zvfh", "-mabi=lp64d", "-std=gnu99",
]
LDFLAGS = ["-static", "-nostdlib", "-nostartfiles", "-lm", "-lgcc",
           "-T", "./common/test.ld"]


def cflags(bench_dir: str) -> list[str]:
    return [*BASE_CFLAGS, f"-I./{bench_dir}"]


# --- Agent workspace (on the riscv_build container) ------------------------
# Container-internal paths; cluster/cluster.yaml bind-mounts host dirs onto
# them (${AETHER_WORKDIR}/work/{kernel,build,sim}). Override in lockstep with
# that yaml if you change them.
AGENT_WORK_DIR = os.environ.get("AETHER_AGENT_WORK_DIR", "/tmp/aether-kernel")
BUILD_WORK_DIR = os.environ.get("AETHER_BUILD_WORK_DIR", "/tmp/aether-build")
SIM_WORK_DIR = os.environ.get("AETHER_SIM_WORK_DIR", "/tmp/aether-sim")

# --- Resources -------------------------------------------------------------
LLM_RESOURCE = 1
BASH_RESOURCE = 0.1
RISCV_BUILD_RESOURCE = 1
VERILATOR_RUN_RESOURCE = 1
CHISEL_BUILD_RESOURCE = 1

# --- LLM -------------------------------------------------------------------
# The 159 loop iterations reported in our results ran on claude-fable-5-1
# and claude-opus-4-7; the default is now Opus 5.5 for subsequent runs.
LLM_MODEL = "claude-opus-5-5"
LLM_EXTRA_CLI_ARGS = ["--effort", "high"]
LLM_TIMEOUT_SECONDS = 1800
LLM_SYSTEM_MESSAGE = (
    "You are an expert RISC-V Vector (RVV 1.0) programmer — assembly and "
    "intrinsics — optimizing kernels for accelerated RISC-V SoCs."
)

# --- Loop ------------------------------------------------------------------
MAX_ITERS = 10
CHISEL_BUILD_TIMEOUT_SECONDS = 60 * 30
BUILD_TIMEOUT_SECONDS = 600
SIM_TIMEOUT_CYCLES = 10_000_000
SIM_TIMEOUT_SECONDS = 900
MAX_FEEDBACK_CHARS = 6000

# --- Experiment database ---------------------------------------------------
DB_PATH = OUT_DIR / "aether.db"

RUNTIME_ENV = {"py_modules": [str(Path(__file__).resolve().parent)]}


# ===========================================================================
# Gemmini (RoCC) — hardware-dependent software collateral
# ===========================================================================
# Gemmini kernels are NOT built from BENCHMARKS_DIR: they live in Gemmini's own
# `gemmini-rocc-tests` tree inside the chipyard container, and one of their
# headers (`gemmini_params.h`) is *generated by Chisel elaboration*. Change the
# Gemmini hardware config and that header — and the spike golden model built
# from it — must be regenerated or every Gemmini binary is silently wrong.
#
# `nodes.gemmini_collateral()` does that regeneration and ships the resulting
# tree back by value; `nodes.build_kernel()` dispatches to it for any Kernel
# whose `target == "gemmini"`.

GEMMINI_ROOT = f"{CHIPYARD_PATH}/generators/gemmini"
GEMMINI_TESTS_DIR = f"{GEMMINI_ROOT}/software/gemmini-rocc-tests"
GEMMINI_LIBGEMMINI_DIR = f"{GEMMINI_ROOT}/software/libgemmini"

# Where Chisel elaboration drops the generated header, relative to the tests
# tree. `gemmini/src/main/scala/gemmini/Controller.scala` writes it from
# `GemminiArrayConfig.generateHeader()` every time a Gemmini tile elaborates.
GEMMINI_PARAMS_REL = "include/gemmini_params.h"

# Setting this env var makes Controller.scala write the header and then
# `System.exit(1)` — i.e. elaboration is aborted the moment the header exists.
# Cheap way to refresh the header without a full `make verilog`; the exit code
# is expected to be nonzero, so the node judges success by the header itself.
GEMMINI_HEADER_ONLY_ENV = "GEMMINI_ONLY_GENERATE_GEMMINI_H"

# --- Which config attributes the regenerated header depends on -------------
# Everything below is read out of the elaborated `GemminiArrayConfig` by
# `generateHeader()`. If a proposed hardware change touches ANY of these, the
# header, `libgemmini.so` and every previously built Gemmini ELF are stale:
#
#   opcodes.opcode          -> XCUSTOM_ACC
#   tileColumns*meshColumns -> DIM                (systolic array dimension)
#   sp_banks                -> BANK_NUM
#   sp_bank_entries         -> BANK_ROWS
#   acc_banks*acc_bank_entries -> ACC_ROWS
#   max_bytes               -> MAX_BYTES, MAX_BLOCK_LEN, MAX_BLOCK_LEN_ACC
#   inputType               -> elem_t / elem_t_max / elem_t_min / full_t,
#                              ELEM_T_IS_FLOAT, ELEM_T_EXP_BITS, ...
#   accType                 -> acc_t, ACC_T_EXP_BITS, ACC_T_SIG_BITS
#   mvin_scale_args         -> HAS_MVIN_SCALE, scale_t, scale_t_bits
#   mvin_scale_acc_args     -> HAS_MVIN_ACC_SCALE, scale_acc_t
#   acc_scale_t / acc_scale_args -> acc_scale_t, ACC_SCALE_IDENTITY, ACC_SCALE()
#   has_training_convs / has_max_pool / has_normalizations / has_first_layer_
#     optimizations         -> the HAS_* feature macros the library #ifdefs on
#
# VLEN/DLEN (the Saturn knobs baked into the config *name*) do NOT appear here:
# a pure vector-unit change leaves the Gemmini header identical, which is why
# `GemminiCollateral.digest` hashes the header *content* rather than the config
# name — an unchanged Gemmini keeps the same digest across Saturn changes.
GEMMINI_HEADER_CONFIG_ATTRS = (
    "opcodes.opcode", "tileColumns", "meshColumns", "tileRows", "meshRows",
    "sp_banks", "sp_bank_entries", "acc_banks", "acc_bank_entries",
    "max_bytes", "inputType", "accType", "spatialArrayOutputType",
    "mvin_scale_args", "mvin_scale_acc_args", "acc_scale_args", "acc_scale_t",
    "has_training_convs", "has_max_pool", "has_normalizations",
    "has_first_layer_optimizations", "has_dw_convs",
)

# --- Gemmini cross-compile (mirrors gemmini-rocc-tests/bareMetalC/Makefile) -
GEMMINI_CC = "riscv64-unknown-elf-gcc"
GEMMINI_BASE_CFLAGS = [
    "-DPREALLOCATE=1", "-DMULTITHREAD=1", "-mcmodel=medany", "-std=gnu99",
    "-O2", "-ffast-math", "-fno-common", "-fno-builtin-printf",
    "-fno-tree-loop-distribute-patterns",
    # V is enabled even though this is the *Gemmini* compile line: the target
    # SoC (GENV256D128GemminiShuttleConfig) carries BOTH a Saturn RVV unit and
    # a Gemmini array, so a Gemmini kernel is allowed to offload part of the
    # work to the vector unit. Without `v` in -march, `<riscv_vector.h>` types
    # (`vint8m2_t`, ...) do not exist and any RVV intrinsic the agent writes
    # fails to compile. Matches Saturn's BASE_CFLAGS above. Verified: the RoCC
    # `.insn`/inline-asm macros in `include/gemmini.h` still assemble with V
    # on, and the emitted .text for the pristine Gemmini kernels is
    # byte-identical to the -march=rv64gc build (no stray auto-vectorization).
    "-march=rv64gcv_zfh_zvfh", "-Wa,-march=rv64gcv_zfh_zvfh",
    "-I.", "-Iriscv-tests", "-Iriscv-tests/env",
    "-Iriscv-tests/benchmarks/common",
    "-DID_STRING=", "-DPRINT_TILE=0",
    "-nostdlib", "-nostartfiles", "-static", "-DBAREMETAL=1",
]
GEMMINI_LDFLAGS = ["-T", "riscv-tests/benchmarks/common/test.ld", "-lm", "-lgcc"]

# Everything the compiler needs from the tests tree, as globs relative to
# GEMMINI_TESTS_DIR. The kernel's own `bench_dir/<main>.c` is added on top.
GEMMINI_SEALED_GLOBS = [
    "include/*.h",
    "rocc-software/src/*.h",
    "riscv-tests/env/*.h",
    "riscv-tests/benchmarks/common/*.c",
    "riscv-tests/benchmarks/common/*.S",
    "riscv-tests/benchmarks/common/*.h",
    "riscv-tests/benchmarks/common/*.ld",
]

# --- Gemmini collateral rebuild --------------------------------------------
# Runs on the `chipyard` worker (the only image with a chipyard checkout).
GEMMINI_PREP_RESOURCE = CHISEL_BUILD_RESOURCE
GEMMINI_HEADER_TIMEOUT_SECONDS = 60 * 12   # header-only elaboration
GEMMINI_ELAB_TIMEOUT_SECONDS = 60 * 25     # full `make verilog` fallback
GEMMINI_SPIKE_TIMEOUT_SECONDS = 60 * 10    # libgemmini.so rebuild
# The loop runs on Verilator and scores the benchmark's own self-check, so the
# spike golden model is not on the critical path. Turn it on only when a cosim
# run is actually wanted (it costs a g++ -O3 of a 75k-line source).
GEMMINI_REBUILD_SPIKE = False
