"""Build / run / score nodes for the kernel-optimization loop.

One iteration is: agent's kernel bytes -> ELF (riscv_build) -> simulator run
(verilator_run) -> Measurement. The simulator itself is built once by
``build_simulator`` and reused by value across every iteration.

Nothing here hard-codes a benchmark: the selected `Kernel` entry supplies the
editable file, the ELF name and the regexes that read the objective out of the
simulator log. Every Ray remote takes those as explicit arguments, so remote
workers never need the driver's selection.

Two targets, one pipeline. Saturn benchmarks are assembled from the local
`BENCHMARKS_DIR` checkout by `collateral.py`. Gemmini ones cannot be: their
`gemmini_params.h` is *generated by Chisel elaboration*, so the tree is a
function of the hardware config and has to be fetched off the chipyard
container — that is what `gemmini_params_rebuild` / `gemmini_collateral` do.
`build_kernel` dispatches between the two on `K().target`.

INTEGRATION NOTE for `loop.py`: it still imports `pristine_kernel` and
`build_inputs` from `collateral`, which only know about `BENCHMARKS_DIR` and
therefore raise for a Gemmini entry. Swap those two call sites for
`nodes.pristine_kernel_for()` / `nodes.build_inputs_for(kernel)` (defined at
the bottom of this file, same signatures) and the loop runs either target
unchanged.

A rule the Gemmini remote has to obey and the others do not: it must not
reference a module global of `nodes` or `constants`. Ray ships this directory
as the single importable package `loop`, so a by-reference pickle of anything
named `nodes.X` / `constants.X` dies on the worker with `ModuleNotFoundError`.
Hence its defaults-by-value signature and its plain-dict return.
"""

from __future__ import annotations

import logging
import re
import shlex
import subprocess
from dataclasses import dataclass

from chia.base.ChiaFunction import ChiaFunction, get
from chia.chipyard.chisel_build_node import ChiselBuildNode
from chia.chipyard.riscv_build_node import RiscvBuildNode
from chia.chipyard.state_def import BuildArtifact, BuildTarget, RunResult
from chia.chipyard.verilator_run_node import VerilatorRunNode

from collateral import build_inputs
from constants import (
    AGENT_WORK_DIR,
    BUILD_TIMEOUT_SECONDS,
    BUILD_WORK_DIR,
    CC,
    CHIPYARD_PATH,
    CHISEL_BUILD_RESOURCE,
    CHISEL_BUILD_TIMEOUT_SECONDS,
    CONFIG_PACKAGE,
    GEMMINI_BASE_CFLAGS,
    GEMMINI_CC,
    GEMMINI_ELAB_TIMEOUT_SECONDS,
    GEMMINI_HEADER_ONLY_ENV,
    GEMMINI_HEADER_TIMEOUT_SECONDS,
    GEMMINI_LDFLAGS,
    GEMMINI_LIBGEMMINI_DIR,
    GEMMINI_PARAMS_REL,
    GEMMINI_PREP_RESOURCE,
    GEMMINI_REBUILD_SPIKE,
    GEMMINI_SEALED_GLOBS,
    GEMMINI_SPIKE_TIMEOUT_SECONDS,
    GEMMINI_TESTS_DIR,
    LDFLAGS,
    RISCV_BUILD_RESOURCE,
    SIM_TIMEOUT_CYCLES,
    SIM_TIMEOUT_SECONDS,
    VERILATOR_RUN_RESOURCE,
    cflags,
)
from context import CONFIG, K

logger = logging.getLogger("aether.nodes")


@dataclass
class Measurement:
    """Outcome of one build+run attempt."""
    ok: bool               # compiled, ran, and the benchmark self-check passed
    kind: str              # "ok" | "build_failure" | "sim_failure" | "incorrect"
    cycles: int | None     # cycles around the kernel (the objective; lower is better)
    instret: int | None
    detail: str


# ---------------------------------------------------------------------------
# Simulator (built once — the hardware is fixed for this loop)
# ---------------------------------------------------------------------------

def build_simulator() -> BuildArtifact:
    """Elaborate + verilate the selected config. ~72s cold on this image."""
    config = CONFIG()
    node = ChiselBuildNode(
        chipyard_path=CHIPYARD_PATH,
        config=config,
        config_package=CONFIG_PACKAGE,
        target=BuildTarget.VERILATOR,
        timeout_seconds=CHISEL_BUILD_TIMEOUT_SECONDS,
    )
    logger.info("Building simulator %s", config)
    art = get(node.build.options(
        resources={"chipyard": CHISEL_BUILD_RESOURCE}).chia_remote(node))
    if not art.success:
        raise RuntimeError(f"simulator build failed (rc={art.returncode})\n"
                           f"{art.stderr[-3000:]}")
    return art


# ---------------------------------------------------------------------------
# Kernel -> ELF
# ---------------------------------------------------------------------------

def _compile_command() -> str:
    """Mirror saturn/benchmarks/Makefile's compile_template for this bench."""
    k = K()
    srcs = [f"{k.bench_dir}/*.c", f"{k.bench_dir}/*.S",
            "common/*.c", "common/*.S", "common/ara/*.c"]
    parts = [CC, *cflags(k.bench_dir), "-o", k.elf_name, *srcs, *LDFLAGS]
    # shell string (not a list) so the globs expand on the build container
    return " ".join(shlex.quote(p) if "*" not in p else p for p in parts)


def build_kernel(kernel: bytes):
    """Compile *kernel* against the sealed collateral; return ProgramBuildArtifact.

    Dispatches on the selected entry's ``target``: Saturn benchmarks are
    assembled from the local ``BENCHMARKS_DIR`` checkout (``collateral.py``),
    Gemmini ones from the hardware-derived tree that
    :func:`gemmini_collateral` fetched off the chipyard container.
    """
    if K().target == "gemmini":
        inputs, command = gemmini_build_inputs(kernel), gemmini_compile_command()
    else:
        inputs, command = build_inputs(kernel), _compile_command()
    node = RiscvBuildNode(timeout_seconds=BUILD_TIMEOUT_SECONDS)
    return get(node.build_program.options(
        resources={"riscv_build": RISCV_BUILD_RESOURCE}).chia_remote(
            node,
            input_files=inputs,
            command=command,
            work_dir=BUILD_WORK_DIR,
            outputs=[K().elf_name],
        ))


# ---------------------------------------------------------------------------
# ELF -> simulator run
# ---------------------------------------------------------------------------

def run_kernel(sim: BuildArtifact, elf: bytes) -> RunResult:
    node = VerilatorRunNode()
    return get(node.run.options(
        resources={"verilator_run": VERILATOR_RUN_RESOURCE}).chia_remote(
            node,
            artifact=sim,
            test_binary_content=elf,
            test_binary_name=K().elf_name,
            work_dir="/tmp/aether-sim",
            timeout_cycles=K().sim_timeout_cycles or SIM_TIMEOUT_CYCLES,
            timeout_seconds=K().sim_timeout_seconds or SIM_TIMEOUT_SECONDS,
            verbose=False,
        ))


def _extract(pattern: str | None, log: str, agg: str) -> int | None:
    """Pull the objective (or minstret) out of the simulator log."""
    if not pattern:
        return None
    vals = [int(m) for m in re.findall(pattern, log)]
    if not vals:
        return None
    if agg == "sum":
        return sum(vals)
    if agg == "last":
        return vals[-1]
    return vals[0]


def measure(build, run: RunResult | None) -> Measurement:
    """Classify one attempt. The self-check inside the benchmark decides
    correctness; we only read the numbers it prints."""
    k = K()
    if build is None or not build.success:
        tail = (build.stderr or build.stdout or "")[-2000:] if build else "no build"
        return Measurement(False, "build_failure", None, None, tail)
    if run is None:
        return Measurement(False, "sim_failure", None, None, "simulator did not run")

    log = f"{run.log or ''}\n{run.out or ''}"
    cycles = _extract(k.cycle_re, log, k.metric_agg)
    instret = _extract(k.instret_re, log, k.metric_agg)

    if not run.success:
        return Measurement(False, "incorrect", cycles, instret,
                           f"simulator rc={run.returncode}; "
                           f"the benchmark's self-check did not pass")
    if cycles is None:
        return Measurement(False, "sim_failure", None, None,
                           f"ran but printed nothing matching {k.cycle_re!r} — "
                           "did the harness change?")
    return Measurement(True, "ok", cycles, instret,
                       f"passed, cycles={cycles}, instret={instret}")


# ---------------------------------------------------------------------------
# Agent workspace (lives on the riscv_build container)
# ---------------------------------------------------------------------------

@ChiaFunction(resources={"riscv_build": 0.05})
def stage_workspace(files: dict[str, bytes], work_dir: str = AGENT_WORK_DIR) -> str:
    """Lay the full benchmark tree down where the agent can read and edit it.

    The agent needs the harness visible for context (what it must stay
    compatible with), but only its edits to the kernel are ever read back.
    """
    import os
    import shutil
    shutil.rmtree(work_dir, ignore_errors=True)
    for rel, content in files.items():
        path = os.path.join(work_dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as fh:
            fh.write(content)
    return f"staged {len(files)} files in {work_dir}"


@ChiaFunction(resources={"riscv_build": 0.05})
def read_kernel(work_dir: str, rel: str) -> bytes:
    """Read back only the kernel. Anything else the agent touched is ignored.

    *rel* is passed explicitly by the driver (the selected entry's
    ``kernel_rel``) — this remote must not depend on the driver's selection.
    """
    import os
    with open(os.path.join(work_dir, rel), "rb") as fh:
        return fh.read()


# ===========================================================================
# Gemmini: hardware-derived software collateral
# ===========================================================================
# A Gemmini kernel cannot be compiled from a checked-in source tree the way a
# Saturn benchmark can. `gemmini_params.h` is *emitted by Chisel elaboration*
# (gemmini/src/main/scala/gemmini/Controller.scala writes
# `GemminiArrayConfig.generateHeader()` into
# `generators/gemmini/software/gemmini-rocc-tests/include/`), so it is a
# function of the hardware config — see `constants.GEMMINI_HEADER_CONFIG_ATTRS`
# for exactly which attributes. Build a kernel against a stale header and the
# result is not a build failure, it is a *silently wrong* binary: the software
# would issue mvins sized for the wrong scratchpad.
#
# So: one node, running on the `chipyard` worker (the only image that has a
# chipyard checkout), regenerates the header for a given config, optionally
# rebuilds spike's `libgemmini.so` from it, and ships the whole compile-ready
# tree back by value. Everything downstream (the riscv_build compile, the
# agent workspace) is then the same generic machinery the Saturn kernels use.


@dataclass
class GemminiCollateral:
    """Compile-ready `gemmini-rocc-tests` tree for one hardware config.

    Attributes:
        config: the Chipyard CONFIG the header was elaborated from.
        ok: the header was produced (or already present) and the tree is usable.
        regenerated: elaboration actually rewrote the header on this call
            (False = the on-disk header was reused; see ``note``).
        params_h: raw bytes of the generated ``include/gemmini_params.h``.
        files: the sealed tree keyed by path *relative to the tests root*
            (``include/gemmini.h``, ``bareMetalC/tiled_matmul_ws.c``,
            ``riscv-tests/benchmarks/common/crt.S``, ...). This dict is exactly
            what ``RiscvBuildNode.build_program`` wants as ``input_files``.
        params_path: worker-side absolute path of the generated header.
        libgemmini_path: worker-side absolute path of the rebuilt
            ``libgemmini.so``; ``""`` when the spike model was not rebuilt.
        libgemmini_digest: sha256 of that ``.so``; ``""`` when not rebuilt.
        digest: sha256 over (config, header content, libgemmini digest). This
            is the cache key: it is content-derived, so a config change that
            leaves Gemmini alone (e.g. a Saturn VLEN change) keeps the same
            digest and no rebuild is wasted.
        note: human-readable trail of what was run.
        log: tail of the elaboration / spike-build output, for diagnosis.
    """
    config: str
    ok: bool
    regenerated: bool
    params_h: bytes
    files: dict[str, bytes]
    params_path: str = ""
    libgemmini_path: str = ""
    libgemmini_digest: str = ""
    digest: str = ""
    note: str = ""
    log: str = ""


@ChiaFunction(resources={"chipyard": GEMMINI_PREP_RESOURCE})
def gemmini_params_rebuild(
    config: str,
    config_package: str = CONFIG_PACKAGE,
    chipyard_path: str = CHIPYARD_PATH,
    tests_dir: str = GEMMINI_TESTS_DIR,
    libgemmini_dir: str = GEMMINI_LIBGEMMINI_DIR,
    params_rel: str = GEMMINI_PARAMS_REL,
    # NOTE: defaults are evaluated on the driver and travel with the pickled
    # function *by value*. The body must not touch a module global of its own:
    # ray ships `nodes`/`constants` as the single importable package `loop`, so
    # anything referenced by module name fails to unpickle on the worker with
    # `ModuleNotFoundError`. Same reason this returns a plain dict rather than
    # a `GemminiCollateral`.
    sealed_globs: list[str] = tuple(GEMMINI_SEALED_GLOBS),
    extra_files: list[str] | None = None,
    rebuild_spike: bool = GEMMINI_REBUILD_SPIKE,
    header_env: str = GEMMINI_HEADER_ONLY_ENV,
    header_timeout: int = GEMMINI_HEADER_TIMEOUT_SECONDS,
    elab_timeout: int = GEMMINI_ELAB_TIMEOUT_SECONDS,
    spike_timeout: int = GEMMINI_SPIKE_TIMEOUT_SECONDS,
    allow_stale: bool = True,
) -> dict:
    """Regenerate `gemmini_params.h` for *config* and collect the tests tree.

    Runs on the ``chipyard`` worker. Every argument is explicit so the remote
    never depends on the driver's selection (same rule as the other nodes).

    Strategy, cheapest first:

    1. ``GEMMINI_ONLY_GENERATE_GEMMINI_H=1 make verilog`` — Controller.scala
       writes the header and immediately ``System.exit(1)``, so make fails on
       purpose and we judge by the header's mtime. Seconds, not minutes.
    2. If that did not touch the header, a plain ``make verilog`` (full
       elaboration; this is what the coexist run did, ~130s).
    3. If elaboration is unavailable/failing and *allow_stale*, fall back to
       whatever header is already on disk and say so in ``note``. This is what
       lets an already-elaborated container be reused without paying again.

    ``rebuild_spike`` additionally copies the fresh header over
    ``software/libgemmini/gemmini_params.h`` and runs ``make install`` there,
    which is what keeps spike/cosim's golden model in sync with the RTL. The
    Verilator loop does not need it (the benchmark self-checks), so it is off
    by default.
    """
    import glob as _glob
    import hashlib
    import os
    import shlex
    import subprocess

    globs = list(sealed_globs)
    params_abs = os.path.join(tests_dir, params_rel)
    notes: list[str] = []
    log_parts: list[str] = []

    def sh(cmd: str, cwd: str, timeout: int, env: dict | None = None):
        # `cd` explicitly: the Chisel generator resolves `headerFilePath`
        # relative to the JVM's cwd ("./generators/gemmini/software/..."), so
        # elaboration MUST run from the chipyard root or the header lands in
        # the wrong place. Not a login shell, for the same reason.
        full = (f"cd {shlex.quote(cwd)} && "
                f"source {shlex.quote(chipyard_path)}/env.sh >/dev/null 2>&1; {cmd}")
        e = dict(os.environ)
        e.update(env or {})
        try:
            pr = subprocess.run(["bash", "-c", full], cwd=cwd, env=e,
                                capture_output=True, text=True, timeout=timeout)
            return pr.returncode, (pr.stdout or "")[-4000:], (pr.stderr or "")[-4000:]
        except subprocess.TimeoutExpired:
            return -1, "", f"timeout after {timeout}s"

    before = os.path.getmtime(params_abs) if os.path.exists(params_abs) else 0.0
    make = (f"make -C {chipyard_path}/sims/verilator "
            f"CONFIG={config} CONFIG_PACKAGE={config_package} verilog")

    # (1) header-only elaboration
    rc, out, err = sh(make, chipyard_path, header_timeout, {header_env: "1"})
    log_parts.append(f"$ {header_env}=1 {make}\nrc={rc}\n{out[-1500:]}\n{err[-1500:]}")
    after = os.path.getmtime(params_abs) if os.path.exists(params_abs) else 0.0
    regenerated = after > before
    notes.append(f"header-only elaboration rc={rc}, "
                 f"header {'rewritten' if regenerated else 'untouched'}")

    # (2) full elaboration
    if not regenerated:
        rc, out, err = sh(make, chipyard_path, elab_timeout)
        log_parts.append(f"$ {make}\nrc={rc}\n{out[-1500:]}\n{err[-1500:]}")
        after = os.path.getmtime(params_abs) if os.path.exists(params_abs) else 0.0
        regenerated = after > before
        notes.append(f"full `make verilog` rc={rc}, "
                     f"header {'rewritten' if regenerated else 'untouched'}")

    def fail(why: str) -> dict:
        return dict(config=config, ok=False, regenerated=False, params_h=b"",
                    files={}, params_path=params_abs,
                    note="; ".join(notes + [why]),
                    log="\n\n".join(log_parts)[-8000:])

    if not os.path.exists(params_abs):
        return fail(f"no {params_abs} after elaboration")
    if not regenerated and not allow_stale:
        return fail("refusing the stale on-disk header (allow_stale=False)")
    if not regenerated:
        notes.append(
            "REUSING the on-disk header: `make verilog` reported nothing to "
            "do, i.e. this container is ALREADY elaborated for this config "
            "(the normal case when `build_simulator()` ran first — its "
            "`make clean` + `make` rewrote the header seconds ago). It is "
            "wrong only if the container was elaborated for a DIFFERENT "
            "Gemmini; pass allow_stale=False to make that an error instead.")

    with open(params_abs, "rb") as fh:
        params_h = fh.read()

    # (3) spike golden model, rebuilt from the same header
    lib_path = lib_digest = ""
    if rebuild_spike:
        lib_params = os.path.join(libgemmini_dir, "gemmini_params.h")
        try:
            with open(lib_params, "wb") as fh:
                fh.write(params_h)
            rc, out, err = sh("make install", libgemmini_dir, spike_timeout)
            log_parts.append(f"$ make install (libgemmini)\nrc={rc}\n"
                             f"{out[-1500:]}\n{err[-1500:]}")
            cand = os.path.join(libgemmini_dir, "libgemmini.so")
            if rc == 0 and os.path.exists(cand):
                lib_path = cand
                with open(cand, "rb") as fh:
                    lib_digest = hashlib.sha256(fh.read()).hexdigest()[:16]
                notes.append(f"libgemmini.so rebuilt+installed ({lib_digest})")
            else:
                notes.append(f"libgemmini.so rebuild FAILED (rc={rc})")
        except OSError as exc:
            notes.append(f"libgemmini.so rebuild skipped: {exc}")

    # (4) the compile-ready tree, keyed relative to the tests root
    files: dict[str, bytes] = {}
    for pattern in globs + list(extra_files or []):
        matches = sorted(_glob.glob(os.path.join(tests_dir, pattern)))
        if not matches:
            notes.append(f"WARNING: nothing matched {pattern!r}")
        for path in matches:
            if os.path.isfile(path):
                with open(path, "rb") as fh:
                    files[os.path.relpath(path, tests_dir)] = fh.read()
    files[params_rel] = params_h          # authoritative, even if a glob got it

    digest = hashlib.sha256(
        b"|".join([config.encode(), params_h, lib_digest.encode()])
    ).hexdigest()[:16]

    return dict(
        config=config, ok=True, regenerated=regenerated, params_h=params_h,
        files=files, params_path=params_abs, libgemmini_path=lib_path,
        libgemmini_digest=lib_digest, digest=digest,
        note="; ".join(notes), log="\n\n".join(log_parts)[-8000:])


# --- driver-side wrapper ---------------------------------------------------

_GEMMINI_MEMO: dict[str, GemminiCollateral] = {}


def gemmini_collateral(config: str | None = None, *, refresh: bool = False,
                       **kwargs) -> GemminiCollateral:
    """Fetch (once per config per process) the Gemmini tree for *config*.

    The selected kernel decides which benchmark source is pulled in on top of
    ``GEMMINI_SEALED_GLOBS``; everything else is config-derived.
    """
    cfg = config or CONFIG()
    k = K()
    extra = list(k.extra_sealed or [])
    if k.main_src:
        extra.append(k.main_src)
    key = f"{cfg}|{'|'.join(sorted(extra))}|{kwargs.get('rebuild_spike', GEMMINI_REBUILD_SPIKE)}"
    if not refresh and key in _GEMMINI_MEMO:
        return _GEMMINI_MEMO[key]
    logger.info("Regenerating Gemmini collateral for %s", cfg)
    col = GemminiCollateral(**get(gemmini_params_rebuild.options(
        resources={"chipyard": GEMMINI_PREP_RESOURCE}).chia_remote(
            config=cfg, extra_files=extra, **kwargs)))
    if not col.ok:
        raise RuntimeError(f"gemmini collateral rebuild failed for {cfg}: "
                           f"{col.note}\n{col.log[-3000:]}")
    logger.info("Gemmini collateral %s: %d files, digest=%s (%s)",
                cfg, len(col.files), col.digest, col.note)
    _GEMMINI_MEMO[key] = col
    return col


def gemmini_compile_command() -> str:
    """Mirror `gemmini-rocc-tests/bareMetalC/Makefile`'s `%-baremetal` rule.

    Run from the task-dir root, which holds the tests tree verbatim, so the
    Makefile's ``-I$(abs_top_srcdir)`` becomes ``-I.`` and
    ``#include "include/gemmini_params.h"`` resolves unchanged.
    """
    k = K()
    srcs = [k.main_src,
            "riscv-tests/benchmarks/common/*.c",
            "riscv-tests/benchmarks/common/*.S"]
    parts = [GEMMINI_CC, *GEMMINI_BASE_CFLAGS, *k.extra_cflags,
             "-o", k.elf_name, *srcs, *GEMMINI_LDFLAGS]
    return " ".join(shlex.quote(p) if "*" not in p else p for p in parts)


def gemmini_pristine_kernel(config: str | None = None) -> bytes:
    """The unmodified agent-owned file, straight out of the rebuilt tree."""
    col = gemmini_collateral(config)
    rel = K().kernel_rel
    try:
        return col.files[rel]
    except KeyError:
        raise RuntimeError(
            f"{rel!r} is not in the Gemmini collateral (have: "
            f"{', '.join(sorted(col.files)[:20])} ...). Widen "
            "GEMMINI_SEALED_GLOBS or fix the entry's kernel_rel.") from None


def gemmini_build_inputs(kernel: bytes, config: str | None = None
                         ) -> dict[str, bytes]:
    """Sealed Gemmini tree + *kernel*, ready for `build_program`.

    Same sealing contract as `collateral.build_inputs`: the agent's bytes
    overwrite exactly one entry and nothing else it touched ever reaches the
    compiler. In particular the benchmark's own `main()` — which holds the CPU
    golden model the self-check compares against — is sealed.
    """
    files = dict(gemmini_collateral(config).files)
    files[K().kernel_rel] = kernel
    return files


def pristine_kernel_for(k=None) -> bytes:
    """Target-dispatching pristine source (Saturn checkout or Gemmini tree).

    `loop.py` still calls `collateral.pristine_kernel()` directly, which only
    knows about `BENCHMARKS_DIR`; use this instead to make it target-agnostic.
    """
    from collateral import pristine_kernel
    return gemmini_pristine_kernel() if (k or K()).target == "gemmini" \
        else pristine_kernel()


def build_inputs_for(kernel: bytes, k=None) -> dict[str, bytes]:
    """Target-dispatching `build_inputs` (see `pristine_kernel_for`)."""
    return (gemmini_build_inputs(kernel) if (k or K()).target == "gemmini"
            else build_inputs(kernel))
